// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMCY5Tv5N3lN9uRJJ1pUChLYkyeQg728',
    appId: '1:260600548807:web:8757f1b27a49b16b79dde2',
    messagingSenderId: '260600548807',
    projectId: 'imei-78551',
    authDomain: 'imei-78551.firebaseapp.com',
    storageBucket: 'imei-78551.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB4aO8y_zKsyGRDVoDzD9MNWqRzYj444w',
    appId: '1:260600548807:android:fac4e0c9f500668479dde2',
    messagingSenderId: '260600548807',
    projectId: 'imei-78551',
    storageBucket: 'imei-78551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6mhg-h50hi4JdBM9qHNlmMENIaHir7w',
    appId: '1:260600548807:ios:f0c3323d1eae93ff79dde2',
    messagingSenderId: '260600548807',
    projectId: 'imei-78551',
    storageBucket: 'imei-78551.firebasestorage.app',
    iosBundleId: 'com.example.imei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX6mhg-h50hi4JdBM9qHNlmMENIaHir7w',
    appId: '1:260600548807:ios:f0c3323d1eae93ff79dde2',
    messagingSenderId: '260600548807',
    projectId: 'imei-78551',
    storageBucket: 'imei-78551.firebasestorage.app',
    iosBundleId: 'com.example.imei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMCY5Tv5N3lN9uRJJ1pUChLYkyeQg728',
    appId: '1:260600548807:web:4bba94a66a661ae779dde2',
    messagingSenderId: '260600548807',
    projectId: 'imei-78551',
    authDomain: 'imei-78551.firebaseapp.com',
    storageBucket: 'imei-78551.firebasestorage.app',
  );

}