// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZy4nTtXTV6NQ1oLqrrgHUQvKB567AgE',
    appId: '1:887147846420:web:ca69ad3af3a480d44f8001',
    messagingSenderId: '887147846420',
    projectId: 'imei-4187d',
    authDomain: 'imei-4187d.firebaseapp.com',
    storageBucket: 'imei-4187d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBopTRjUPhIcP7xDEm8I_93Tg5IYFgtk1Q',
    appId: '1:887147846420:android:28f588a3f21a46bd4f8001',
    messagingSenderId: '887147846420',
    projectId: 'imei-4187d',
    storageBucket: 'imei-4187d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9MRO2ffHcgtX89Ah3ksAE-Rdg21o0-78',
    appId: '1:887147846420:ios:30fd6f33029ee6074f8001',
    messagingSenderId: '887147846420',
    projectId: 'imei-4187d',
    storageBucket: 'imei-4187d.firebasestorage.app',
    iosBundleId: 'com.example.imei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9MRO2ffHcgtX89Ah3ksAE-Rdg21o0-78',
    appId: '1:887147846420:ios:30fd6f33029ee6074f8001',
    messagingSenderId: '887147846420',
    projectId: 'imei-4187d',
    storageBucket: 'imei-4187d.firebasestorage.app',
    iosBundleId: 'com.example.imei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAZy4nTtXTV6NQ1oLqrrgHUQvKB567AgE',
    appId: '1:887147846420:web:d1e8fc37ad355aa64f8001',
    messagingSenderId: '887147846420',
    projectId: 'imei-4187d',
    authDomain: 'imei-4187d.firebaseapp.com',
    storageBucket: 'imei-4187d.firebasestorage.app',
  );
}
